### ISSUE TITLE
I can't open https://luma.enablementadobe.com/content/luma/us/en.html .

### ISSUE THREAD

**Issue by YokoKanai** [AdobeDocs/platform-learn.ja-JP#1]
Issue in ./help/tutorial-web-sdk/validate-with-debugger.md
I can't open https://luma.enablementadobe.com/content/luma/us/en.html .
This is sample site for "Web SDK Tutorial". I can't execute the tutorial.

**Comment by mak-adobe** [comment]
@YokoKanai 現在はアクセスできるようですが、如何でしょうか？

**Comment by YokoKanai** [comment]
今、アクセスしてみたのですが以下の画面のまま、進みません
キャッシュを消して、ChromeとFireFoxで試したのですが。。。

***@***.***

念のためEdgeでも試しましたが、やはり同じ状態です。
VPNをつなぐと、アクセスできます。VPNを切断すると画面が上記白いまま、読み込みができない状況です。

よろしくお願いいたします。
金井

**Comment by YokoKanai** [comment]
今、アクセスしてみたところ、アクセスできるようになりました！
以下すべての環境で、Chrome、FireFox、Edgeともに表示されました
・会社PC＋一般回線
・会社PC＋VPN　
・個人所有PC＋一般回線
一次的なトラブルだったとは思うのですが何Lumaサイトが参照するファイルが配置されている
サーバーの設定が変わりました？


金井

From: Yoko Kanai
Sent: Friday, July 21, 2023 3:17 PM
To: AdobeDocs/platform-learn.ja-JP ***@***.***>; AdobeDocs/platform-learn.ja-JP ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [AdobeDocs/platform-learn.ja-JP] I can't open https://luma.enablementadobe.com/content/luma/us/en.html . (Issue #1)

今、アクセスしてみたのですが以下の画面のまま、進みません
キャッシュを消して、ChromeとFireFoxで試したのですが。。。

***@***.***

念のためEdgeでも試しましたが、やはり同じ状態です。
VPNをつなぐと、アクセスできます。VPNを切断すると画面が上記白いまま、読み込みができない状況です。

よろしくお願いいたします。
金井

**Comment by mak-adobe** [comment]
@YokoKanai こちら（北米）でも先週繋がりにくい状況が一度だけ発生し、その後毎日確認していましたが、再現できなくなりました。一旦クローズしますが、また繋がりにくい状況が発生した際は再オープンをお願いします。

**Comment by YokoKanai** [comment]
@Mak ***@***.***>さん
ご連絡ありがとうございます。
北米でも発生していたんですね。もしまた発生しましたら、連絡しますので、その際はよろしくお願いします。

金井
